services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  user-service:
    build: ./backend/services/user-service
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      MONGO_URI: mongodb://mongodb:27017/user-service-db
      RABBITMQ_URL: amqp://rabbitmq
      PORT: 3001
    restart: always

  notification-service:
    build: ./backend/services/notification-service
    container_name: notification-service
    ports:
      - "3006:3006"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq
      PORT: 3006
    restart: always

  product-service:
    build: ./backend/services/product-service
    container_name: product-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/product-service-db
      RABBITMQ_URL: amqp://rabbitmq
      JWT_SECRET: mysecret
      PORT: 3002
    restart: always

  order-service:
    build: ./backend/services/order-service
    container_name: order-service
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      MONGO_URI: mongodb://mongodb:27017/order-service-db
      RABBITMQ_URL: amqp://rabbitmq
      PRODUCT_SERVICE_URL: http://product-service:3002
      PORT: 3003
    restart: always

  payment-service:
    build: ./backend/services/payment-service
    container_name: payment-service
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq
      PORT: 3004
    restart: always

  api-gateway:
    build: ./backend/services/api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
      - notification-service
    restart: always

  nginx:
  image: nginx:latest
  container_name: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  depends_on:
    - api-gateway
  restart: always
volumes:
  mongo_data: